# Instrument - an object which represents a compiled WaveLang instrument

import utils

Import("*")

env = env.Clone()

env.Append(CPPPATH = ["#source"])

sources = utils.enumerate_files(env, ".", utils.SOURCE_EXTENSIONS)

objects = []
for source in sources:
	obj = env.StaticObject(source)
	objects += obj

instrument_library = env.StaticLibrary("instrument", objects)

instrument_installed = env.Install("../bin", instrument_library)
env.Alias("instrument", instrument_installed)
