#ifndef WAVELANG_EXECUTION_GRAPH_NATIVE_MODULES_NATIVE_MODULES_CONTROLLER_H__
#define WAVELANG_EXECUTION_GRAPH_NATIVE_MODULES_NATIVE_MODULES_CONTROLLER_H__

#include "common/common.h"

#include "execution_graph/native_module.h"

const uint32 k_native_modules_controller_library_id = 6;
wl_library(k_native_modules_controller_library_id, "controller");

extern const s_native_module_uid k_native_module_controller_get_note_id_uid;
wl_native_module(k_native_module_controller_get_note_id_uid, "controller_get_note_id")
wl_runtime_only
void native_module_controller_get_note_id(real32 wl_out_return &result);

extern const s_native_module_uid k_native_module_controller_get_note_velocity_uid;
wl_native_module(k_native_module_controller_get_note_velocity_uid, "controller_get_note_velocity")
wl_runtime_only
void native_module_controller_get_note_velocity(real32 wl_out_return &result);

extern const s_native_module_uid k_native_module_controller_get_note_press_duration_uid;
wl_native_module(k_native_module_controller_get_note_press_duration_uid, "controller_get_note_press_duration")
wl_runtime_only
void native_module_controller_get_note_press_duration(real32 wl_out_return &result);

extern const s_native_module_uid k_native_module_controller_get_note_release_duration_uid;
wl_native_module(k_native_module_controller_get_note_release_duration_uid, "controller_get_note_release_duration")
wl_runtime_only
void native_module_controller_get_note_press_duration(real32 wl_out_return &result);

#endif // WAVELANG_EXECUTION_GRAPH_NATIVE_MODULES_NATIVE_MODULES_CONTROLLER_H__
