# Compiler - compiles source code into binary files which can be loaded by the runtime

import utils

Import("*")

env = env.Clone()

env.Append(CPPPATH = ["#source"])

sources = utils.enumerate_files(env, ".", utils.SOURCE_EXTENSIONS)

objects = []
for source in sources:
	obj = env.StaticObject(source)
	objects += obj

compiler_library = env.StaticLibrary("compiler", objects)

compiler_installed = env.Install("../bin", compiler_library)
env.Alias("compiler", compiler_installed)
